[tool.poetry]
name = "finance_app"
version = "0.1.0"
description = "Demo course project"
authors = ["Ваше Имя <email@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.2"
openpyxl = "^3.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1"
pytest-mock = "^3.14"
mypy = "^1.10"
flake8 = "^7.0"
isort = "^5.13"
black = "^24.4"

# --- форматирование ---------------------------------------------------------
[tool.black]
line-length = 119
target-version = ["py311"]
exclude = '''
/(
    \.git
)/
'''

[tool.isort]
profile = "black"
line_length = 119
skip_gitignore = true

# --- статический анализ -----------------------------------------------------
[tool.mypy]
python_version = "3.11"
disallow_untyped_defs = true
warn_return_any = true
exclude = "(venv|\\.git)"
